version: "3"

vars:
  DATABASE_URL: "postgres://postgres:foobarbaz@localhost:5432/postgres"
  IMAGE_REPO: sidpalas/devops-directive-docker-course-api-golang
  IMAGE_TAG: foobarbaz
  SERVICE_RELEASE_TAG: services/go/api-golang

includes:
  utils:
    taskfile: ../../../utils/Taskfile.yaml
    dir: ../../../utils

tasks:
  install:
    desc: "download dependencies"
    cmds:
      - go mod tidy

  run:
    desc: "download dependencies"
    cmds:
      - echo $PWD
      - ls
      - DATABASE_URL={{.DATABASE_URL}} go run main.go

  test:
    desc: run tests
    cmds:
      - go test ./test -v
