version: "3"

vars:
  IMAGE_REPO: sidpalas/devops-directive-kubernetes-course-load-generator-python
  IMAGE_TAG: foobarbaz
  SERVICE_RELEASE_TAG: services/python/load-generator-python

includes:
  utils:
    taskfile: ../../../utils/Taskfile.yaml
    dir: ../../../utils

tasks:
  install:
    desc: Install load generator dependencies
    cmds:
      - poetry install --no-root

  install-ci:
    desc: install/download package dependencies
    cmds:
      - poetry install --no-root

  run:
    desc: Start load generator
    cmds:
      # api-golang is listening on port 8000
      - API_URL=http://localhost:8000/ DELAY_MS=100 poetry run python main.py

  test:
    desc: run tests
    cmds:
      - poetry run pytest
