version: "3"

vars:
  RED: '\033[0;31m'
  GREEN: '\033[0;32m'
  YELLOW: '\033[1;33m'
  BLUE: '\033[0;34m'
  NC: '\033[0m'

tasks:
  default:
    desc: Show available compute management commands
    silent: true
    cmds:
      - |
        echo "Compute Management Tasks"
        echo ""
        echo "Available tasks:"
        echo "  task run-migrator  - Run database migrations"
        echo ""
        echo "Examples:"
        echo "  task run-migrator"

  check-terraform:
    internal: true
    silent: true
    preconditions:
      - sh: command -v terraform
        msg: "Error: terraform command not found"

  run-migrator:
    desc: Run database migrations using ECS task
    deps: [check-terraform]
    prompt: |
      This will run the migrator task on ECS.

      Make sure:
      - Database is accessible
      - AWS credentials are configured

      Continue?
    cmds:
      - echo -e "{{.BLUE}}Running migrator task...{{.NC}}"
      - terraform output -raw migrator_run_command | bash
      - echo ""
      - echo -e "{{.GREEN}}✓ Migrator task started{{.NC}}"
      - echo "Check AWS ECS console for task status and logs."
